# Generated by Django 4.2.17 on 2025-01-09 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_collaboraterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='email',
            new_name='sender_email',
        ),
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='name',
            new_name='sender_name',
        ),
        migrations.RemoveField(
            model_name='collaboraterequest',
            name='read',
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
