# Generated by Django 4.2.17 on 2025-01-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rating_review_rating_updated_at_alter_rating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
