# Generated by Django 4.2.17 on 2025-01-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='updated_at',
        ),
    ]
